#
# (C) Copyright 2013-2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= generic.o
obj-y	+= lowlevel.o
obj-y	+= cpu.o
obj-y	+= cse.o
obj-y	+= clock.o
obj-$(CONFIG_SYS_PIT_TIMER)	+= timer.o
obj-$(CONFIG_S32V234_LPDDR2)	+= lpddr2.o
obj-$(CONFIG_GICSUPPORT)	+= gicsupport.o
obj-$(CONFIG_S32V234_DDR3)	+= ddr3.o
obj-$(CONFIG_S32V234_FLASH)	+= qspi_driver.o
obj-$(CONFIG_MP)		+= mp.o
obj-$(CONFIG_OF_LIBFDT)		+= fdt.o
