#
# (C) Copyright 2013-2016 Freescale Semiconductor, Inc.
# (C) Copyright 2016-2017 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_S32V234)	+= clock.o
obj-$(CONFIG_ARCH_S32V234)	+= cpu.o
obj-$(CONFIG_ARCH_S32V234)	+= cse.o
obj-$(CONFIG_ARCH_S32V234)	+= lowlevel.o
obj-$(CONFIG_ARCH_S32V234)	+= soc.o
obj-$(CONFIG_SYS_PIT_TIMER)	+= timer.o
obj-$(CONFIG_S32V234_LPDDR2)	+= lpddr2.o
obj-$(CONFIG_GICSUPPORT)	+= gicsupport.o
obj-$(CONFIG_S32V234_DDR3)	+= ddr3.o
obj-$(CONFIG_S32V234_FLASH)	+= qspi_driver.o
obj-$(CONFIG_MP)		+= mp.o
obj-$(CONFIG_OF_LIBFDT)		+= fdt.o
obj-$(CONFIG_FSL_DCU_FB)	+= dcu.o
