# SPDX-License-Identifier:	GPL-2.0+
#
# (C) Copyright 2018 NXP
#

obj-y					+= clock.o
obj-y					+= soc.o
obj-y					+= sram.o
obj-$(CONFIG_S32V234_FLASH)		+= qspi_driver.o
obj-$(CONFIG_S32V234_USES_FLASH)	+= qspi_iomux.o
