#
# (C) Copyright 2013-2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ARCH_S32V244)	+= generic.o
obj-$(CONFIG_ARCH_S32V244)	+= pinmux.o
obj-$(CONFIG_ARCH_S32V244)	+= lowlevel.o
obj-$(CONFIG_ARCH_S32V244)	+= cpu.o
obj-$(CONFIG_ARCH_S32V244)	+= cse.o
obj-$(CONFIG_ARCH_S32V244)	+= clock.o
obj-$(CONFIG_SYS_PIT_TIMER)	+= timer.o
obj-$(CONFIG_S32V244_LPDDR4)	+= lpddr4.o
obj-$(CONFIG_GICSUPPORT)	+= gicsupport.o
obj-$(CONFIG_S32V244_DDR3)	+= ddr3.o
obj-$(CONFIG_S32V244_FLASH)	+= qspi_driver.o
obj-$(CONFIG_MP)		+= mp.o
obj-$(CONFIG_OF_LIBFDT)		+= fdt.o
