#
# (C) Copyright 2013-2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := s32v234evb.o
obj-$(CONFIG_SJA1105) += sja1105_cfg.o
obj-$(CONFIG_S32_LPDDR2) += lpddr2_config.o

#########################################################################
