# SPDX-License-Identifier: GPL-2.0+ OR BSD-3-Clause
#
# Copyright 2023 NXP
#

# NXP S32G PFE Ethernet accelerator driver
obj-y += pfeng.o \
	 pfeng_fw.o \
	 pfeng_netif.o \
	 pfeng_mdio.o \
	 pfe_hw.o \

