# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2020 NXP
#

obj-y := campps32v2.o
obj-$(CONFIG_S32_LPDDR2) += lpddr2_config.o
obj-$(CONFIG_SJA1105) += sja1105_cfg.o

#########################################################################
