#
# Copyright 2022 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y				+= ../
obj-$(CONFIG_NXP_S32GRDB_BOARD)	+= s32gxxxardb.o
obj-$(CONFIG_NXP_S32GEVB_BOARD)	+= s32gxxxaevb.o

ccflags-y += -Iboard/nxp/s32-cc/include
