#
# (C) Copyright 2013-2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := mmu.o
obj-y   += mac57d5xhevb.o

#########################################################################
