#
# Copyright 2018, 2020 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := s32v234ccpb.o
obj-$(CONFIG_SJA1105) += sja1105_cfg.o

#########################################################################
