#
# (C) Copyright 2017 MicroSys Electronics GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y   := mpxs32v234.o s32v_ocotp.o cmd_mac.o

#########################################################################
