/* SPDX-License-Identifier: GPL 2.0 */
/*
 *  Copyright (c) 2020 Imagination Technologies Limited
 *  Copyright 2018-2020 NXP
 */

/**
 * @addtogroup  dxgr_PFE_TMU
 * @{
 *
 * @file		pfe_tmu_csr.h
 * @brief		The TMU LITE module registers definition file (s32g).
 * @details		Applicable for IP versions listed below.
 *
 */

#ifndef _TMU_CSR_H_
#define _TMU_CSR_H_

#ifndef PFE_CBUS_H_
#error Missing cbus.h
#endif /* PFE_CBUS_H_ */

/*	Supported IPs. Defines are validated within pfe_cbus.h. */
#if (PFE_CFG_IP_VERSION != PFE_CFG_IP_VERSION_FPGA_5_0_4) && \
	(PFE_CFG_IP_VERSION != PFE_CFG_IP_VERSION_NPU_7_14)
#error Unsupported IP version
#endif /* PFE_CFG_IP_VERSION */

#define TMU_VERSION	     (CBUS_TMU_CSR_BASE_ADDR + 0x000U)
#define TMU_INQ_WATERMARK    (CBUS_TMU_CSR_BASE_ADDR + 0x004U)
#define TMU_PHY_INQ_PKTPTR   (CBUS_TMU_CSR_BASE_ADDR + 0x008U)
#define TMU_PHY_INQ_PKTINFO  (CBUS_TMU_CSR_BASE_ADDR + 0x00cU)
#define TMU_PHY_INQ_STAT     (CBUS_TMU_CSR_BASE_ADDR + 0x010U)
#define TMU_PHY_QUEUE_SEL    (CBUS_TMU_CSR_BASE_ADDR + 0x014U)
#define TMU_CURQ_PTR	     (CBUS_TMU_CSR_BASE_ADDR + 0x018U)
#define TMU_CURQ_PKT_CNT     (CBUS_TMU_CSR_BASE_ADDR + 0x01cU)
#define TMU_CURQ_DROP_CNT    (CBUS_TMU_CSR_BASE_ADDR + 0x020U)
#define TMU_CURQ_TRANS_CNT   (CBUS_TMU_CSR_BASE_ADDR + 0x024U)
#define TMU_CURQ_QSTAT	     (CBUS_TMU_CSR_BASE_ADDR + 0x028U)
#define TMU_HW_PROB_CFG_TBL0 (CBUS_TMU_CSR_BASE_ADDR + 0x02cU)
#define TMU_HW_PROB_CFG_TBL1 (CBUS_TMU_CSR_BASE_ADDR + 0x030U)
#define TMU_CURQ_DEBUG	     (CBUS_TMU_CSR_BASE_ADDR + 0x034U)
#define TMU_CTRL	     (CBUS_TMU_CSR_BASE_ADDR + 0x038U)
#define TMU_BMU_INQ_ADDR     (CBUS_TMU_CSR_BASE_ADDR + 0x03cU)
#define TMU_AFULL_THRES	     (CBUS_TMU_CSR_BASE_ADDR + 0x040U)
#define TMU_BMU_BUF_SIZE     (CBUS_TMU_CSR_BASE_ADDR + 0x044U)
#define TMU_MAX_BUF_CNT	     (CBUS_TMU_CSR_BASE_ADDR + 0x048U)
#define TMU_TEQ_CTRL	     (CBUS_TMU_CSR_BASE_ADDR + 0x04cU)
#define TMU_BMU2_INQ_ADDR    (CBUS_TMU_CSR_BASE_ADDR + 0x050U)
#define TMU_DDR_DATA_OFFSET  (CBUS_TMU_CSR_BASE_ADDR + 0x054U)
#define TMU_LMEM_BUF_SIZE    (CBUS_TMU_CSR_BASE_ADDR + 0x058U)
#define TMU_LMEM_DATA_OFFSET (CBUS_TMU_CSR_BASE_ADDR + 0x05cU)
#define TMU_LMEM_BASE_ADDR   (CBUS_TMU_CSR_BASE_ADDR + 0x060U)

#define TMU_PHY0_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x064U)
#define TMU_PHY1_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x068U)
#define TMU_PHY2_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x06cU)
#define TMU_PHY3_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x070U)
#define TMU_PHY4_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x074U)
#define TMU_PHY5_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x078U)
#define TMU_PHY6_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x07cU)
#define TMU_PHY7_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x080U)
#define TMU_PHY8_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x084U)
#define TMU_PHY9_INQ_ADDR  (CBUS_TMU_CSR_BASE_ADDR + 0x088U)
#define TMU_PHY10_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x08cU)
#define TMU_PHY11_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x090U)
#define TMU_PHY12_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x094U)
#define TMU_PHY13_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x098U)
#define TMU_PHY14_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x09cU)
#define TMU_PHY15_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x0a0U)
#define TMU_PHY16_INQ_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x0a4U)
#define TMU_PHYN_INQ_ADDR(n)		(TMU_PHY0_INQ_ADDR + ((n) * 4U)

#define TMU_PHY0_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0acU)
#define TMU_PHY1_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0b0U)
#define TMU_PHY2_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0b4U)
#define TMU_PHY3_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0b8U)
#define TMU_PHY4_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0bcU)
#define TMU_PHY5_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0c0U)
#define TMU_PHY6_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0c4U)
#define TMU_PHY7_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0c8U)
#define TMU_PHY8_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0ccU)
#define TMU_PHY9_TDQ_IIFG_CFG  (CBUS_TMU_CSR_BASE_ADDR + 0x0d0U)
#define TMU_PHY10_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0d4U)
#define TMU_PHY11_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0d8U)
#define TMU_PHY12_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0dcU)
#define TMU_PHY13_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0e0U)
#define TMU_PHY14_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0e4U)
#define TMU_PHY15_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0e8U)
#define TMU_PHY16_TDQ_IIFG_CFG (CBUS_TMU_CSR_BASE_ADDR + 0x0ecU)

#define TMU_PHY0_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x0f0U)
#define TMU_PHY1_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x0f4U)
#define TMU_PHY2_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x0f8U)
#define TMU_PHY3_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x0fcU)
#define TMU_PHY4_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x100U)
#define TMU_PHY5_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x104U)
#define TMU_PHY6_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x108U)
#define TMU_PHY7_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x10cU)
#define TMU_PHY8_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x110U)
#define TMU_PHY9_TDQ_CTRL  (CBUS_TMU_CSR_BASE_ADDR + 0x114U)
#define TMU_PHY10_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x118U)
#define TMU_PHY11_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x11cU)
#define TMU_PHY12_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x120U)
#define TMU_PHY13_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x124U)
#define TMU_PHY14_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x128U)
#define TMU_PHY15_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x12cU)
#define TMU_PHY16_TDQ_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x130U)

#define TMU_CNTX_ACCESS_CTRL (CBUS_TMU_CSR_BASE_ADDR + 0x134U)
#define TMU_CNTX_ADDR	     (CBUS_TMU_CSR_BASE_ADDR + 0x138U)
#define TMU_CNTX_DATA	     (CBUS_TMU_CSR_BASE_ADDR + 0x13cU)
#define TMU_CNTX_CMD	     (CBUS_TMU_CSR_BASE_ADDR + 0x140U)

#define TMU_DBG_BUS_TOP	 (CBUS_TMU_CSR_BASE_ADDR + 0x144U)
#define TMU_DBG_BUS_PP0	 (CBUS_TMU_CSR_BASE_ADDR + 0x148U)
#define TMU_DBG_BUS_PP1	 (CBUS_TMU_CSR_BASE_ADDR + 0x14cU)
#define TMU_DBG_BUS_PP2	 (CBUS_TMU_CSR_BASE_ADDR + 0x150U)
#define TMU_DBG_BUS_PP3	 (CBUS_TMU_CSR_BASE_ADDR + 0x154U)
#define TMU_DBG_BUS_PP4	 (CBUS_TMU_CSR_BASE_ADDR + 0x158U)
#define TMU_DBG_BUS_PP5	 (CBUS_TMU_CSR_BASE_ADDR + 0x15cU)
#define TMU_DBG_BUS_PP6	 (CBUS_TMU_CSR_BASE_ADDR + 0x160U)
#define TMU_DBG_BUS_PP7	 (CBUS_TMU_CSR_BASE_ADDR + 0x164U)
#define TMU_DBG_BUS_PP8	 (CBUS_TMU_CSR_BASE_ADDR + 0x168U)
#define TMU_DBG_BUS_PP9	 (CBUS_TMU_CSR_BASE_ADDR + 0x16cU)
#define TMU_DBG_BUS_PP10 (CBUS_TMU_CSR_BASE_ADDR + 0x170U)
#define TMU_DBG_BUS_PP11 (CBUS_TMU_CSR_BASE_ADDR + 0x174U)
#define TMU_DBG_BUS_PP12 (CBUS_TMU_CSR_BASE_ADDR + 0x178U)
#define TMU_DBG_BUS_PP13 (CBUS_TMU_CSR_BASE_ADDR + 0x17cU)
#define TMU_DBG_BUS_PP14 (CBUS_TMU_CSR_BASE_ADDR + 0x180U)
#define TMU_DBG_BUS_PP15 (CBUS_TMU_CSR_BASE_ADDR + 0x184U)
#define TMU_DBG_BUS_PP16 (CBUS_TMU_CSR_BASE_ADDR + 0x188U)

#define TMU_METER_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x190U)
#define TMU_METER_CFG0 (CBUS_TMU_CSR_BASE_ADDR + 0x194U)
#define TMU_METER_CFG1 (CBUS_TMU_CSR_BASE_ADDR + 0x198U)
#define TMU_METER_CMD  (CBUS_TMU_CSR_BASE_ADDR + 0x19cU)

#define TLITE_TDQ_PHY0_CSR_BASE_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x1000U)
#define TLITE_TDQ_PHY1_CSR_BASE_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x2000U)
#define TLITE_TDQ_PHY2_CSR_BASE_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x3000U)
#define TLITE_TDQ_PHY3_CSR_BASE_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x4000U)
#define TLITE_TDQ_PHY4_CSR_BASE_ADDR (CBUS_TMU_CSR_BASE_ADDR + 0x5000U)
#define TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) \
	(TLITE_TDQ_PHY0_CSR_BASE_ADDR + ((n) * 0x1000U))

#define TLITE_SCHED0_BASE_OFFSET 0x000U
#define TLITE_SCHED1_BASE_OFFSET 0x100U
#define TLITE_SCHED_OFFSET_MASK	 0xfffU

#define TLITE_PHY0_SCHED0_BASE_ADDR \
	(TLITE_TDQ_PHY0_CSR_BASE_ADDR + TLITE_SCHED0_BASE_OFFSET)
#define TLITE_PHY0_SCHED1_BASE_ADDR \
	(TLITE_TDQ_PHY0_CSR_BASE_ADDR + TLITE_SCHED1_BASE_OFFSET)
#define TLITE_PHY0_SHP0_BASE_ADDR (TLITE_TDQ_PHY0_CSR_BASE_ADDR + 0x200U)
#define TLITE_PHY0_SHP1_BASE_ADDR (TLITE_TDQ_PHY0_CSR_BASE_ADDR + 0x300U)
#define TLITE_PHY0_SHP2_BASE_ADDR (TLITE_TDQ_PHY0_CSR_BASE_ADDR + 0x400U)
#define TLITE_PHY0_SHP3_BASE_ADDR (TLITE_TDQ_PHY0_CSR_BASE_ADDR + 0x500U)

#define TLITE_PHYN_SCHED0_BASE_ADDR(n) \
	(TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x000U)
#define TLITE_PHYN_SCHED1_BASE_ADDR(n) \
	(TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x100U)
#define TLITE_PHYN_SHP0_BASE_ADDR(n) (TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x200U)
#define TLITE_PHYN_SHP1_BASE_ADDR(n) (TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x300U)
#define TLITE_PHYN_SHP2_BASE_ADDR(n) (TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x400U)
#define TLITE_PHYN_SHP3_BASE_ADDR(n) (TLITE_TDQ_PHYN_CSR_BASE_ADDR(n) + 0x500U)

#define TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) \
	(TLITE_PHYN_SCHED0_BASE_ADDR(n) + ((m) * 0x100U))
#define TLITE_PHYN_SHPM_BASE_ADDR(n, m) \
	(TLITE_PHYN_SHP0_BASE_ADDR(n) + ((m) * 0x100U))

#define TLITE_PHYN_SCHM_CTRL(n, m) \
	(TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) + TMU_SCH_CTRL)
#define TLITE_PHYN_SCHM_QL_WGHT(n, m, l) \
	(TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) + TMU_SCH_QN_WGHT(l))
#define TLITE_PHYN_SCHM_Q_ALLOCL(n, m, l) \
	(TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) + TMU_SCH_Q_ALLOCN(l))
#define TLITE_PHYN_SCHM_BIT_RATE(n, m) \
	(TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) + TMU_SCH_BIT_RATE)
#define TLITE_PHYN_SCHM_POS(n, m) \
	(TLITE_PHYN_SCHEDM_BASE_ADDR(n, m) + TMU_SCH_POS)

#define TLITE_PHYN_SHPM_CTRL(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_CTRL)
#define TLITE_PHYN_SHPM_WGHT(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_WGHT)
#define TLITE_PHYN_SHPM_MAX_CREDIT(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_MAX_CREDIT)
#define TLITE_PHYN_SHPM_CTRL2(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_CTRL2)
#define TLITE_PHYN_SHPM_MIN_CREDIT(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_MIN_CREDIT)
#define TLITE_PHYN_SHPM_STATUS(n, m) \
	(TLITE_PHYN_SHPM_BASE_ADDR(n, m) + TMU_SHP_STATUS)

/*	TMU/TLITE Scheduler */
#define TMU_SCH_CTRL	    (0x00U)
#define TMU_SCH_Q0_WGHT	    (0x20U)
#define TMU_SCH_Q1_WGHT	    (0x24U)
#define TMU_SCH_Q2_WGHT	    (0x28U)
#define TMU_SCH_Q3_WGHT	    (0x2cU)
#define TMU_SCH_Q4_WGHT	    (0x30U)
#define TMU_SCH_Q5_WGHT	    (0x34U)
#define TMU_SCH_Q6_WGHT	    (0x38U)
#define TMU_SCH_Q7_WGHT	    (0x3cU)
#define TMU_SCH_QN_WGHT(n)  (TMU_SCH_Q0_WGHT + ((n) * 4U))
#define TMU_SCH_Q_ALLOC0    (0x40U)
#define TMU_SCH_Q_ALLOC1    (0x44U)
#define TMU_SCH_Q_ALLOCN(n) (TMU_SCH_Q_ALLOC0 + ((n) * 4U))
#define TMU_SCH_BIT_RATE    (0x48U)
#define TMU_SCH_POS	    (0x54U)

/*	TMU/TLITE Shaper */
#define TMU_SHP_CTRL	   (0x00U)
#define TMU_SHP_WGHT	   (0x04U)
#define TMU_SHP_MAX_CREDIT (0x08U)
#define TMU_SHP_CTRL2	   (0x0cU)
#define TMU_SHP_MIN_CREDIT (0x10U)
#define TMU_SHP_STATUS	   (0x14U)

/*	Properties */
#define TLITE_PHYS_CNT	     5U /*	Number of PHYs */
#define TLITE_PHY_QUEUES_CNT 8U /*	Number of queues per PHY */
#define TLITE_SCH_INPUTS_CNT 8U /*	Number of inputs per scheduler */

#endif /* _TMU_CSR_H_ */

/** @}*/
