#
# (C) Copyright 2013-2016 Freescale Semiconductor, Inc.
# (C) Copyright 2016-2017 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y				+= clock.o
obj-y				+= cpu.o
obj-$(CONFIG_S32V234)		+= cse.o
obj-y				+= lowlevel.o
obj-y				+= soc.o
obj-$(CONFIG_SYS_PIT_TIMER)	+= timer.o
obj-$(CONFIG_S32V234_LPDDR2)	+= lpddr2.o
obj-$(CONFIG_S32V244_LPDDR4)	+= lpddr4.o
obj-$(CONFIG_GICSUPPORT)	+= gicsupport.o
obj-$(CONFIG_S32V234_DDR3)	+= ddr3.o
obj-$(CONFIG_S32V234_FLASH)	+= qspi_driver.o
obj-$(CONFIG_S32V234_USES_FLASH)	+= qspi_common.o
obj-$(CONFIG_MP)		+= mp.o
obj-$(CONFIG_OF_LIBFDT)		+= fdt.o
obj-$(CONFIG_FSL_DCU_FB)	+= dcu.o
