#
# (C) Copyright 2013-2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Idenfifier:	GPL-2.0+
#

obj-y   := s32v234pcie.o
obj-$(CONFIG_S32_LPDDR2) += lpddr2_config.o

#########################################################################
